// @ts-nocheck
const { Component } = React;

const EMPTY = {q:'',manufacturer:'',winch_type:'',capacity_kg:'',speed_range:'',suspension:'',speed_count:'',vfd:'',encoder_type:'',power_range:'',cantilever_required_kg:'',lift_height_required_m:'',groove_shape:'',undercut_angle:'',sheave_diameter_mm:'',rope_count:'',rope_diameter_mm:'',starts_per_hour:'',brake_voltage:'',weight_kg:'',placement_type:''};
const fmt=(v,u='')=>(v===null||v===undefined||v==='')?'—':String(v).replace('.',',')+(u?' '+u:'');
const arr=v=>Array.isArray(v)&&v.length?v.join(', '):'—';
function params(f,extra={}){const p=new URLSearchParams();Object.keys(f).forEach(k=>{const v=f[k];if(v===''||v==null)return;if(k==='speed_range'){const z=String(v).split('|');p.set('speed_min',z[0]);p.set('speed_max',z[1]);}else if(k==='power_range'){const z=String(v).split('|');p.set('power_min',z[0]);p.set('power_max',z[1]);}else p.set(k,v)});Object.keys(extra).forEach(k=>p.set(k,String(extra[k])));return p}

function MachineVisual(){return <div className="machine-visual"><div className="machine-body"><i/></div><div className="machine-wheel"><i/></div><div className="machine-shaft"/><span>ФОТО МОДЕЛИ</span></div>}
function Field({label,value,onChange,children,disabled=false}){return <label className={'field '+(disabled?'disabled':'')}><b>{label}</b><select value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}>{children}</select></label>}
function Section({id,title,subtitle,open,onToggle,children}){return <div className={'f-section '+(open?'open':'')}><button type="button" className="f-head" onClick={onToggle}><em>{id}</em><span><b>{title}</b><small>{subtitle}</small></span><i>{open?'−':'+'}</i></button><div className="f-body">{children}</div></div>}
function ProductCard({p,selected,onCompare,onDetails,filters}){return <article className="product-card">
  <div className="media"><MachineVisual/><span className="match">✓ Подходит</span></div>
  <div className="pc-body"><div className="pc-head"><span>{p.manufacturer}</span><h3>{p.model}</h3><small>{p.winch_type||'Тип уточняется'}</small></div>
  <div className="spec-grid"><div><small>Грузоподъёмность</small><b>{fmt(p.capacity_kg,'кг')}</b></div><div><small>Скорость</small><b>{fmt(p.speed_m_s,'м/с')}</b></div><div><small>Мощность</small><b>{fmt(p.power_kw,'кВт')}</b></div><div><small>Подвес</small><b>{arr(p.suspensions)}</b></div><div><small>КВШ</small><b>{fmt(p.sheave_diameter_mm,'мм')}</b></div><div><small>Канаты</small><b>{arr(p.rope_counts)} × {arr(p.rope_diameters_mm)} мм</b></div></div>
  <div className="mini-spec"><span>Нагрузка <b>{fmt(p.max_cantilever_load_kg,'кг')}</b></span><span>Масса <b>{fmt(p.weight_kg,'кг')}</b></span><span>Угол <b>{fmt(p.undercut_angle_normalized,'°')}</b></span></div>
  <div className="pc-actions"><button className={'compare '+(selected?'active':'')} onClick={()=>onCompare(p)} title="Сравнить">⇄</button><button className="detail" onClick={()=>onDetails(p.id)}>Подробнее</button><a className="quote" href={'/product/'+p.id+'/inquiry?'+params(filters).toString()}>Запросить цену →</a></div>
  </div></article>}

class DetailsModal extends Component<any,any>{constructor(p){super(p);this.state={data:null,error:''}}componentDidMount(){fetch('/api/products/'+this.props.id).then(r=>r.json()).then(data=>this.setState({data})).catch(()=>this.setState({error:'Не удалось загрузить карточку'}))}render(){const p=this.state.data;return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)this.props.onClose()}}><div className="modal"><button className="close" onClick={this.props.onClose}>×</button>{!p?<div className="loading">{this.state.error||'Загружаем технический паспорт…'}</div>:<><div className="detail-hero"><MachineVisual/><div><span className="eyebrow">{p.manufacturer}</span><h2>{p.model}</h2><p>{p.winch_type}</p><div className="chips"><b>{fmt(p.capacity_kg,'кг')}</b><b>{fmt(p.speed_m_s,'м/с')}</b><b>{fmt(p.power_kw,'кВт')}</b></div></div></div><div className="tech-cols">
  <Tech title="Основные" rows={[['Грузоподъёмность',fmt(p.capacity_kg,'кг')],['Скорость',fmt(p.speed_m_s,'м/с')],['Подвес',arr(p.suspensions)],['Количество скоростей',p.speed_count]]}/>
  <Tech title="Привод" rows={[['Мощность',fmt(p.power_kw,'кВт')],['Ток',fmt(p.nominal_current_a,'A')],['Обороты',fmt(p.nominal_rpm,'об/мин')],['Частота',fmt(p.frequency_hz,'Гц')]]}/>
  <Tech title="КВШ и канаты" rows={[['Диаметр КВШ',fmt(p.sheave_diameter_mm,'мм')],['Форма ручья',p.groove_shape],['Угол подреза',p.undercut_angle],['Канаты',arr(p.rope_counts)+' × '+arr(p.rope_diameters_mm)]]}/>
  <Tech title="Эксплуатация" rows={[['Консольная нагрузка',fmt(p.max_cantilever_load_kg,'кг')],['Высота подъёма',fmt(p.max_lift_height_m,'м')],['Включений/час',p.starts_per_hour],['Масса',fmt(p.weight_kg,'кг')]]}/>
</div><div className="modal-actions"><button className={'detail '+(this.props.compared?'dark':'')} onClick={()=>this.props.onCompare(p)}>{this.props.compared?'В сравнении':'Добавить к сравнению'}</button><a className="quote" href={'/product/'+p.id+'/inquiry?'+params(this.props.filters).toString()}>Запросить цену →</a></div></>}</div></div>}}
function Tech({title,rows}){return <section className="tech"><h4>{title}</h4>{rows.map((r,i)=><div key={i}><span>{r[0]}</span><b>{r[1]??'—'}</b></div>)}</section>}

class CompareModal extends Component<any,any>{constructor(p){super(p);this.state={data:null}}componentDidMount(){this.load(this.props.items)}componentDidUpdate(prev){if(prev.items.map(x=>x.id).join(',')!==this.props.items.map(x=>x.id).join(','))this.load(this.props.items)}load(items){fetch('/api/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:items.map(x=>x.id)})}).then(r=>r.json()).then(data=>this.setState({data}))}render(){const d=this.state.data;return <div className="overlay"><div className="modal compare-modal"><button className="close" onClick={this.props.onClose}>×</button><span className="eyebrow">Инженерное сравнение</span><h2>Сравнение {this.props.items.length} моделей</h2>{!d?<div className="loading">Формируем сравнение…</div>:<div className="compare-scroll"><table><thead><tr><th>Параметр</th>{d.items.map(p=><th key={p.id}><MachineVisual/><small>{p.manufacturer}</small><b>{p.model}</b><button onClick={()=>this.props.onRemove(p.id)}>×</button></th>)}</tr></thead><tbody>{d.fields.map(f=><tr key={f.key}><td>{f.label}</td>{d.items.map(p=><td key={p.id}>{fmt(p[f.key],f.unit)}</td>)}</tr>)}</tbody></table></div>}</div></div>}}

class App extends Component<any,any>{
 constructor(p){super(p);this.state={meta:null,filters:{...EMPTY},items:[],total:0,loading:true,more:false,error:'',sections:{main:true,drive:true,operation:false,ropes:false,electric:false},compare:[],details:null,compareOpen:false,mobile:false};this.qTimer=null}
 componentDidMount(){fetch('/api/meta').then(r=>r.json()).then(meta=>{this.setState({meta},()=>this.search())}).catch(()=>this.setState({error:'Не удалось загрузить справочники',loading:false}))}
 setF(k,v){const f={...this.state.filters,[k]:v};if(k==='winch_type'&&String(v).indexOf('Безредукторная')===0)f.speed_count='1';if(k==='groove_shape')f.undercut_angle='';this.setState({filters:f});if(k==='q'){clearTimeout(this.qTimer);this.qTimer=setTimeout(()=>this.search(),350)}}
 search(append=false){const off=append?this.state.items.length:0;this.setState(append?{more:true}:{loading:true,error:''});fetch('/api/search?'+params(this.state.filters,{limit:12,offset:off})).then(r=>{if(!r.ok)throw 0;return r.json()}).then(d=>this.setState({items:append?this.state.items.concat(d.items):d.items,total:d.total,loading:false,more:false})).catch(()=>this.setState({error:'Не удалось выполнить подбор',loading:false,more:false}))}
 reset(){this.setState({filters:{...EMPTY}},()=>this.search())}
 toggleCompare(p){const a=this.state.compare;const found=a.some(x=>x.id===p.id);this.setState({compare:found?a.filter(x=>x.id!==p.id):(a.length<4?a.concat([p]):a)})}
 render(){const {meta,filters,items,total,loading,sections,compare}=this.state;const setSec=k=>this.setState({sections:{...sections,[k]:!sections[k]}});const speedDisabled=String(filters.winch_type).indexOf('Безредукторная')===0;const angles=meta&&meta.undercut_angles&&meta.undercut_angles[filters.groove_shape]||[];return <div>
<header><div className="wrap header"><div className="brand"><i>L</i><b>LIFTORG</b><small>B2B engineering</small></div><nav><a href="#catalog">Подбор</a><a href="#catalog">Каталог</a><a href="#workflow">Как работает</a></nav><a className="outline" href="#catalog">Начать подбор →</a></div></header>
<section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow orange">Профессиональный каталог</span><h1>Инженерный подбор<br/><em>лифтовых лебёдок</em></h1><p>Фильтруйте 838 исполнений по техническим параметрам, сравнивайте 2–4 модели и формируйте запрос производителю.</p><div className="hero-actions"><a className="quote big" href="#catalog">Подобрать лебёдку →</a><b>838 <small>исполнений в базе</small></b></div></div><div className="hero-cards"><div className="floating back"><small>Каталог</small><b>Nidec · Sicor · Torindrive</b></div><div className="floating front"><small>Сценарий инженера</small><b>Параметры → модель → запрос → цена</b><div><span>1000 кг</span><span>1,0–1,6 м/с</span><span>2:1</span><span>КВШ 400</span></div></div></div></div></section>
<section id="workflow" className="workflow"><div className="wrap">{[['01','Параметры','Укажите требования'],['02','Модель','Выберите вариант'],['03','Запрос цены','Опросный лист'],['04','Стоимость','Расчёт условий']].map((x,i)=><React.Fragment key={x[0]}><div className={'step '+(i===0?'active':'')}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span></div>{i<3&&<hr/>}</React.Fragment>)}</div></section>
<section id="catalog" className="catalog"><div className="wrap grid"><aside className={this.state.mobile?'filters show':'filters'}><div className="filter-title"><span><small className="eyebrow orange">Параметры проекта</small><h2>Фильтры</h2></span><button onClick={()=>this.reset()}>↻</button><button className="mob-x" onClick={()=>this.setState({mobile:false})}>×</button></div><label className="search">⌕<input value={filters.q} onChange={e=>this.setF('q',e.target.value)} placeholder="Модель или ID"/></label>
<Section id="01" title="Основное" subtitle="Тип, производитель, проект" open={sections.main} onToggle={()=>setSec('main')}><div className="fields"><Field label="Производитель" value={filters.manufacturer} onChange={v=>this.setF('manufacturer',v)}><option value="">Любой</option>{meta&&meta.manufacturers.map(x=><option key={x}>{x}</option>)}</Field><Field label="Тип лебёдки" value={filters.winch_type} onChange={v=>this.setF('winch_type',v)}><option value="">Любой тип</option>{meta&&meta.winch_types.map(x=><option key={x}>{x}</option>)}</Field><Field label="Грузоподъёмность" value={filters.capacity_kg} onChange={v=>this.setF('capacity_kg',v)}><option value="">Любая</option>{meta&&meta.capacities.map(x=><option key={x} value={x}>{fmt(x,'кг')}</option>)}</Field><Field label="Скорость" value={filters.speed_range} onChange={v=>this.setF('speed_range',v)}><option value="">Любой диапазон</option>{meta&&meta.speed_ranges.map(x=><option key={x.label} value={x.min+'|'+x.max}>{x.label}</option>)}</Field></div></Section>
<Section id="02" title="Привод" subtitle="Подвес, мощность, ЧП, энкодер" open={sections.drive} onToggle={()=>setSec('drive')}><div className="fields"><Field label="Кратность подвески" value={filters.suspension} onChange={v=>this.setF('suspension',v)}><option value="">Любая</option>{meta&&meta.suspensions.map(x=><option key={x}>{x}</option>)}</Field><Field label="Мощность" value={filters.power_range} onChange={v=>this.setF('power_range',v)}><option value="">Любой диапазон</option>{meta&&meta.power_ranges.map(x=><option key={x.label} value={x.min+'|'+x.max}>{x.label}</option>)}</Field><Field label="Количество скоростей" value={filters.speed_count} disabled={speedDisabled} onChange={v=>this.setF('speed_count',v)}><option value="">1 или 2</option><option value="1">1 скорость</option><option value="2">2 скорости</option></Field><Field label="Наличие ЧП" value={filters.vfd} onChange={v=>this.setF('vfd',v)}><option value="">Неважно</option>{meta&&meta.vfd_options.map(x=><option key={x}>{x}</option>)}</Field><Field label="Энкодер" value={filters.encoder_type} onChange={v=>this.setF('encoder_type',v)}><option value="">Неважно</option>{meta&&meta.encoder_types.map(x=><option key={x}>{x}</option>)}</Field></div></Section>
<Section id="03" title="Эксплуатация" subtitle="Нагрузка, высота, размещение" open={sections.operation} onToggle={()=>setSec('operation')}><div className="fields"><Field label="Консольная нагрузка" value={filters.cantilever_required_kg} onChange={v=>this.setF('cantilever_required_kg',v)}><option value="">Неважно</option>{meta&&meta.cantilever_limits.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</Field><Field label="Высота подъёма" value={filters.lift_height_required_m} onChange={v=>this.setF('lift_height_required_m',v)}><option value="">Неважно</option>{meta&&meta.lift_height_limits.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</Field><Field label="Тип размещения" value={filters.placement_type} onChange={v=>this.setF('placement_type',v)}><option value="">Неважно</option>{meta&&meta.placement_types.map(x=><option key={x}>{x}</option>)}</Field></div></Section>
<Section id="04" title="КВШ и канаты" subtitle="Геометрия и канаты" open={sections.ropes} onToggle={()=>setSec('ropes')}><div className="fields"><Field label="Форма ручья" value={filters.groove_shape} onChange={v=>this.setF('groove_shape',v)}><option value="">Любая</option>{meta&&meta.groove_shapes.map(x=><option key={x}>{x}</option>)}</Field><Field label="Угол подреза" value={filters.undercut_angle} disabled={!filters.groove_shape} onChange={v=>this.setF('undercut_angle',v)}><option value="">Любой</option>{angles.map(x=><option key={x} value={x}>{x}°</option>)}</Field><Field label="Диаметр КВШ" value={filters.sheave_diameter_mm} onChange={v=>this.setF('sheave_diameter_mm',v)}><option value="">Любой</option>{meta&&meta.sheave_diameters.map(x=><option key={x} value={x}>{fmt(x,'мм')}</option>)}</Field><Field label="Количество канатов" value={filters.rope_count} onChange={v=>this.setF('rope_count',v)}><option value="">Любое</option>{meta&&meta.rope_counts.map(x=><option key={x} value={x}>{x}</option>)}</Field><Field label="Диаметр каната" value={filters.rope_diameter_mm} onChange={v=>this.setF('rope_diameter_mm',v)}><option value="">Любой</option>{meta&&meta.rope_diameters.map(x=><option key={x} value={x}>{fmt(x,'мм')}</option>)}</Field></div></Section>
<Section id="05" title="Электрика и прочее" subtitle="Тормоз, включения, масса" open={sections.electric} onToggle={()=>setSec('electric')}><div className="fields"><Field label="Включений/час" value={filters.starts_per_hour} onChange={v=>this.setF('starts_per_hour',v)}><option value="">Любое</option>{meta&&meta.starts_per_hour.map(x=><option key={x} value={x}>{x}</option>)}</Field><Field label="Питание тормоза" value={filters.brake_voltage} onChange={v=>this.setF('brake_voltage',v)}><option value="">Любое</option>{meta&&meta.brake_voltages.map(x=><option key={x}>{x}</option>)}</Field><Field label="Масса" value={filters.weight_kg} onChange={v=>this.setF('weight_kg',v)}><option value="">Любая</option>{meta&&meta.weights.map(x=><option key={x} value={x}>{fmt(x,'кг')}</option>)}</Field></div></Section>
<button className="apply" onClick={()=>{this.search();this.setState({mobile:false})}}>Показать подходящие <b>{total||''}</b> →</button></aside>
<div className="results"><div className="result-head"><div><span className="eyebrow orange">Подходящие модели</span><h2>Результаты подбора</h2></div><div><button className="mobile-filter" onClick={()=>this.setState({mobile:true})}>☰ Фильтры</button><span className="count">Найдено <b>{total}</b></span></div></div><div className="note">ⓘ Некоторые инженерные поля заполнены не для всей номенклатуры. Отсутствующие значения система не придумывает.</div>{this.state.error&&<div className="error">{this.state.error}</div>}{loading?<div className="skeletons">{[1,2,3,4].map(x=><i key={x}/>)}</div>:items.length?<div className="products">{items.map(p=><ProductCard key={p.id} p={p} filters={filters} selected={compare.some(x=>x.id===p.id)} onCompare={p=>this.toggleCompare(p)} onDetails={id=>this.setState({details:id})}/>)}</div>:<div className="empty"><b>Подходящих моделей не найдено</b><span>Измените параметры или сбросьте фильтры.</span></div>}{items.length<total&&!loading&&<div className="more"><button disabled={this.state.more} onClick={()=>this.search(true)}>{this.state.more?'Загрузка…':'Показать ещё ↓'}</button><small>Показано {items.length} из {total}</small></div>}</div></div></section>
{compare.length>0&&<div className="compare-dock"><div>{compare.map(p=><span key={p.id}><small>{p.manufacturer}</small><b>{p.model}</b><button onClick={()=>this.toggleCompare(p)}>×</button></span>)}</div><aside><small>{compare.length} из 4</small><button disabled={compare.length<2} onClick={()=>this.setState({compareOpen:true})}>⇄ Сравнить</button></aside></div>}
{this.state.details&&<DetailsModal id={this.state.details} filters={filters} compared={compare.some(x=>x.id===this.state.details)} onClose={()=>this.setState({details:null})} onCompare={p=>this.toggleCompare(p)}/>} {this.state.compareOpen&&<CompareModal items={compare} onClose={()=>this.setState({compareOpen:false})} onRemove={id=>this.setState({compare:compare.filter(x=>x.id!==id)})}/>}<footer><div className="wrap"><b>LIFTORG B2B</b><span>React engineering UI 3.0 · источник данных: актуальные файлы заказчика</span><a href="/legacy">Резервная серверная версия</a></div></footer></div>}
}
ReactDOM.render(<App/>,document.getElementById('root'));
